hobbyloop/hobbyloop-server

root/api-gateway-server/src/main/resources/application.yml, root/company-service/build.gradle, root/company-service/src/main/java/com/example/companyservice/CompanyServiceApplication.java, root/company-service/src/main/java/com/example/companyservice/client/PayServiceClient.java, root/company-service/src/main/java/com/example/companyservice/client/dto/CompanyRatePlanRequestDto.java, root/company-service/src/main/java/com/example/companyservice/common/exception/ApiException.java, root/company-service/src/main/java/com/example/companyservice/common/exception/ApiExceptionEntity.java, root/company-service/src/main/java/com/example/companyservice/common/exception/ExceptionEnum.java, root/company-service/src/main/java/com/example/companyservice/common/util/Utils.java, root/company-service/src/main/java/com/example/companyservice/controller/ApiExceptionController.java, root/company-service/src/main/java/com/example/companyservice/controller/CompanyController.java, root/company-service/src/main/java/com/example/companyservice/dto/BaseResponseDto.java, root/company-service/src/main/java/com/example/companyservice/dto/request/CompanyUpdateRequestDto.java, root/company-service/src/main/java/com/example/companyservice/entity/Company.java, root/company-service/src/main/java/com/example/companyservice/entity/CreateStatusEnum.java, root/company-service/src/main/java/com/example/companyservice/repository/CompanyRepository.java, root/company-service/src/main/java/com/example/companyservice/service/CompanyService.java, root/company-service/src/main/java/com/example/companyservice/service/CompanyServiceImpl.java, root/company-service/src/main/resources/application.yml, root/pay-service/src/main/java/com/example/payservice/controller/CompanyRatePlanController.java, root/pay-service/src/main/java/com/example/payservice/dto/BaseResponseDto.java, root/pay-service/src/main/java/com/example/payservice/dto/request/CompanyRatePlanRequestDto.java, root/pay-service/src/main/java/com/example/payservice/entity/CompanyPaymentType.java, root/pay-service/src/main/java/com/example/payservice/entity/CompanyRatePlan.java, root/pay-service/src/main/java/com/example/payservice/entity/EntryAuthorityEnum.java, root/pay-service/src/main/java/com/example/payservice/repository/CompanyRatePlanRepository.java, root/pay-service/src/main/java/com/example/payservice/service/CompanyRatePlanService.java, root/pay-service/src/main/java/com/example/payservice/service/CompanyRatePlanServiceImpl.java, root/pay-service/src/main/resources/application.yml
작업요약
- 업체 등록 정보 신청 기능 추가
- FeignClient 사용해서 pay-service에 요금제 정보 생성
=> feat: 업체 정보 등록 신청 기능 구현

root/company-service/src/main/java/com/example/companyservice/controller/CenterController.java, root/company-service/src/main/java/com/example/companyservice/controller/CompanyController.java, root/company-service/src/main/java/com/example/companyservice/dto/request/BreakHourListDto.java, root/company-service/src/main/java/com/example/companyservice/dto/request/CenterCreateRequestDto.java, root/company-service/src/main/java/com/example/companyservice/dto/request/OperatingHourListDto.java, root/company-service/src/main/java/com/example/companyservice/entity/Center.java, root/company-service/src/main/java/com/example/companyservice/entity/CenterBreakHour.java, root/company-service/src/main/java/com/example/companyservice/entity/CenterOpeningHour.java, root/company-service/src/main/java/com/example/companyservice/entity/Company.java, root/company-service/src/main/java/com/example/companyservice/entity/DayEnum.java, root/company-service/src/main/java/com/example/companyservice/repository/CenterBreakHourRepository.java, root/company-service/src/main/java/com/example/companyservice/repository/CenterOpeningHourRepository.java, root/company-service/src/main/java/com/example/companyservice/repository/CenterRepository.java, root/company-service/src/main/java/com/example/companyservice/service/CenterService.java, root/company-service/src/main/java/com/example/companyservice/service/CenterServiceImpl.java, root/company-service/src/main/java/com/example/companyservice/service/CompanyService.java, root/company-service/src/main/java/com/example/companyservice/service/CompanyServiceImpl.java, root/company-service/src/main/resources/application.yml, root/pay-service/src/main/resources/application.yml
요약
- 시설 등록 기능 추가
- 시설 운영시간, 휴식시간 기능 추가
- 시설 로고 등록이랑 홍보 사진 저장 기능 추가 안됨, S3 버킷 생성되면 추가할 예정
=> feat: 시설 등록 기능 추가

root/company-service/build.gradle, root/company-service/src/main/java/com/example/companyservice/client/TicketServiceClient.java, root/company-service/src/main/java/com/example/companyservice/client/dto/TicketResponseDto.java, root/company-service/src/main/java/com/example/companyservice/common/exception/ExceptionEnum.java, root/company-service/src/main/java/com/example/companyservice/controller/CenterController.java, root/company-service/src/main/java/com/example/companyservice/dto/request/HourRequestDto.java, root/company-service/src/main/java/com/example/companyservice/dto/response/CenterHomeResponseDto.java, root/company-service/src/main/java/com/example/companyservice/entity/Center.java, root/company-service/src/main/java/com/example/companyservice/entity/CenterOperatingHour.java, root/company-service/src/main/java/com/example/companyservice/entity/QuickButton.java, root/company-service/src/main/java/com/example/companyservice/repository/CenterBreakHourRepository.java, root/company-service/src/main/java/com/example/companyservice/repository/CenterOpeningHourRepository.java, root/company-service/src/main/java/com/example/companyservice/repository/CenterOperatingHourRepository.java, root/company-service/src/main/java/com/example/companyservice/repository/QuickButtonRepository.java, root/company-service/src/main/java/com/example/companyservice/service/CenterService.java, root/company-service/src/main/java/com/example/companyservice/service/CenterServiceImpl.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/BaseResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/TicketResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/TicketRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java, root/ticket-service/src/main/resources/application.yml
- 시설 상세 조회
- 즐겨찾기 버튼 리스트 조회
- 이용권 리스트 조회
=> feat: 시설 관리자 홈 페이지 시설 정보 상세 조회

root/company-service/src/main/java/com/example/companyservice/controller/CenterController.java, root/company-service/src/main/java/com/example/companyservice/dto/response/CenterCompanyResponseDto.java, root/company-service/src/main/java/com/example/companyservice/dto/response/CompanyResponseDto.java, root/company-service/src/main/java/com/example/companyservice/entity/Company.java, root/company-service/src/main/java/com/example/companyservice/service/CenterService.java, root/company-service/src/main/java/com/example/companyservice/service/CenterServiceImpl.java
=> feat: 시설 관리 수업 및 이용권 페이지 시설, 업체 정보 상세 조회

root/company-service/src/main/java/com/example/companyservice/controller/CenterController.java, root/company-service/src/main/java/com/example/companyservice/dto/request/CenterUpdateRequestDto.java, root/company-service/src/main/java/com/example/companyservice/dto/response/CenterCompanyResponseDto.java, root/company-service/src/main/java/com/example/companyservice/entity/Center.java, root/company-service/src/main/java/com/example/companyservice/entity/QuickButton.java, root/company-service/src/main/java/com/example/companyservice/repository/CenterBreakHourRepository.java, root/company-service/src/main/java/com/example/companyservice/repository/CenterOperatingHourRepository.java, root/company-service/src/main/java/com/example/companyservice/repository/QuickButtonRepository.java, root/company-service/src/main/java/com/example/companyservice/service/CenterService.java, root/company-service/src/main/java/com/example/companyservice/service/CenterServiceImpl.java
- 시설 정보 수정
- 시설 운영시간, 휴식시간 수정
- 즐겨찾기 버튼 목록 수정
=> feat: 시설 정보 수정

root/api-gateway-server/src/main/resources/application.yml, root/company-service/src/main/java/com/example/companyservice/client/PayServiceClient.java, root/company-service/src/main/java/com/example/companyservice/client/TicketServiceClient.java, root/company-service/src/main/java/com/example/companyservice/client/dto/request/CompanyRatePlanRequestDto.java, root/company-service/src/main/java/com/example/companyservice/client/dto/response/TicketResponseDto.java, root/company-service/src/main/java/com/example/companyservice/controller/CenterController.java, root/company-service/src/main/java/com/example/companyservice/dto/response/CenterHomeResponseDto.java, root/company-service/src/main/java/com/example/companyservice/dto/response/CenterInfoResponseDto.java, root/company-service/src/main/java/com/example/companyservice/service/CenterService.java, root/company-service/src/main/java/com/example/companyservice/service/CenterServiceImpl.java, root/company-service/src/main/java/com/example/companyservice/service/CompanyServiceImpl.java, root/ticket-service/build.gradle, root/ticket-service/src/main/java/com/example/ticketservice/TicketServiceApplication.java, root/ticket-service/src/main/java/com/example/ticketservice/client/CompanyServiceClient.java, root/ticket-service/src/main/java/com/example/ticketservice/client/dto/response/CenterInfoResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/client/dto/response/HourResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/AdminTicketResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/Ticket.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java
=> feat: 시설 관리 페이지 이용권 리스트 조회

root/api-gateway-server/src/main/resources/application.yml, root/company-service/src/main/java/com/example/companyservice/client/TicketServiceClient.java, root/company-service/src/main/java/com/example/companyservice/common/exception/ExceptionEnum.java, root/company-service/src/main/java/com/example/companyservice/common/util/Utils.java, root/company-service/src/main/java/com/example/companyservice/controller/ApiExceptionController.java, root/company-service/src/main/java/com/example/companyservice/controller/CenterController.java, root/company-service/src/main/java/com/example/companyservice/controller/CompanyController.java, root/company-service/src/main/java/com/example/companyservice/dto/response/CenterInfoDetailResponseDto.java, root/company-service/src/main/java/com/example/companyservice/entity/Bookmark.java, root/company-service/src/main/java/com/example/companyservice/repository/BookmarkRepository.java, root/company-service/src/main/java/com/example/companyservice/service/CenterService.java, root/company-service/src/main/java/com/example/companyservice/service/CenterServiceImpl.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/ReviewController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/AdminTicketResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/ReviewRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/service/ReviewService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/ReviewServiceImpl.java
- 시설 정보 조회
- 시설 운영시간 조회
- 리뷰 카운트 수 조회
- 북마크 여부 조회
=> feat: IOS 시설 정보 상세 조회

root/api-gateway-server/.gitignore, root/api-gateway-server/build.gradle, root/api-gateway-server/src/main/java/com/example/apigatewayserver/config/CorsConfig.java, root/api-gateway-server/src/main/java/com/example/apigatewayserver/filter/JWTUtil.java, root/api-gateway-server/src/main/java/com/example/apigatewayserver/filter/JwtAuthenticationFilter.java, root/api-gateway-server/src/main/resources/application.yml, root/company-service/.gitignore, root/company-service/build.gradle, root/company-service/src/main/java/com/example/companyservice/common/exception/ExceptionEnum.java, root/company-service/src/main/java/com/example/companyservice/config/SecurityConfig.java, root/company-service/src/main/java/com/example/companyservice/controller/ViewController.java, root/company-service/src/main/java/com/example/companyservice/entity/Company.java, root/company-service/src/main/java/com/example/companyservice/entity/Role.java, root/company-service/src/main/java/com/example/companyservice/repository/CompanyRepository.java, root/company-service/src/main/java/com/example/companyservice/security/JWTUtil.java, root/company-service/src/main/java/com/example/companyservice/security/LoginSuccessHandler.java, root/company-service/src/main/java/com/example/companyservice/security/OAuth2UserDetailsService.java, root/company-service/src/main/java/com/example/companyservice/security/OAuthUserDetails.java, root/company-service/src/main/resources/application.yml, root/company-service/src/main/resources/templates/index.html
- 카카오 로그인 구현
- 네이버 로그인 구현
- 로그인 성공시 access_token, refresh_token 발급 후 리다이렉트
=> feat: 카카오, 네이버 로그인 구현

root/company-service/src/main/java/com/example/companyservice/client/TicketServiceClient.java, root/company-service/src/main/java/com/example/companyservice/client/dto/response/BookmarkTicketResponseDto.java, root/company-service/src/main/java/com/example/companyservice/controller/CenterController.java, root/company-service/src/main/java/com/example/companyservice/dto/response/BookmarkCenterResponseDto.java, root/company-service/src/main/java/com/example/companyservice/repository/BookmarkRepository.java, root/company-service/src/main/java/com/example/companyservice/repository/QuickButtonRepository.java, root/company-service/src/main/java/com/example/companyservice/service/CenterService.java, root/company-service/src/main/java/com/example/companyservice/service/CenterServiceImpl.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/BookmarkTicketResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java
- 북마크한 시설 리스트 조회
- 시설별 이용권 리스트 조회
=> feat: 북마크한 시설 리스트 조회

root/api-gateway-server/src/main/resources/application.yml, root/company-service/src/main/java/com/example/companyservice/common/exception/ExceptionEnum.java, root/ticket-service/src/main/java/com/example/ticketservice/common/exception/ExceptionEnum.java, root/ticket-service/src/main/java/com/example/ticketservice/common/util/Utils.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/ReviewController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/ReviewListResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/ReviewResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/ReviewImage.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/ReviewLike.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/ReviewImageRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/ReviewLikeRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/service/ReviewService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/ReviewServiceImpl.java
- 이용권 별 리뷰 리스트 조회
- 좋아요 여부
- 좋아요 수
- 대댓글 수
- 리뷰 이미지 조회
=> feat: 앱 이용권 별 리뷰 리스트 조회

root/company-service/src/main/java/com/example/companyservice/controller/CenterController.java, root/company-service/src/main/java/com/example/companyservice/repository/bookmark/BookmarkRepositoryCustom.java, root/company-service/src/main/java/com/example/companyservice/repository/bookmark/BookmarkRepositoryImpl.java, root/company-service/src/main/java/com/example/companyservice/service/CenterService.java, root/company-service/src/main/java/com/example/companyservice/service/CenterServiceImpl.java, root/ticket-service/src/main/java/com/example/ticketservice/TicketServiceApplication.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/ReviewController.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/AdminTicketResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/ReviewResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/ReviewImageRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/review/ReviewRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/review/ReviewRepositoryCustom.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/review/ReviewRepositoryImpl.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/ticket/TicketRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/ticket/TicketRepositoryCustom.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/ticket/TicketRepositoryImpl.java, root/ticket-service/src/main/java/com/example/ticketservice/service/ReviewService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/ReviewServiceImpl.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java
- 시설 관리 페이지 이용권 페이지네이션
- 시설 관리 페이지 리뷰 페이지네이션
- IOS 리뷰 페이지네이션
=> feat: 페이지네이션 적용

root/company-service/src/main/java/com/example/companyservice/client/TicketServiceClient.java, root/company-service/src/main/java/com/example/companyservice/client/dto/response/BookmarkScoreTicketResponseDto.java, root/company-service/src/main/java/com/example/companyservice/dto/response/BookmarkCenterResponseDto.java, root/company-service/src/main/java/com/example/companyservice/entity/Center.java, root/company-service/src/main/java/com/example/companyservice/service/CenterServiceImpl.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/AdminReviewResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/BookmarkScoreTicketResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/Ticket.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/review/ReviewRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/service/ReviewServiceImpl.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java
평점을 그때그때 시설과 이용권 테이블에 저장하는게 아닌 필요할 때 조회해오도록 변경
=> fix: 시설, 이용권 평점 조회 로직 수정

root/ticket-service/src/main/java/com/example/ticketservice/client/CompanyServiceClient.java, root/ticket-service/src/main/java/com/example/ticketservice/client/dto/response/OriginalBusinessResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/client/dto/response/OriginalCenterResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/TicketDetailResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java
- 이용권 상세 조회 구현
- 추후에 이용권에 등록된 수업 목록도 포함해야함
=> feat: 이용권 상세 조회 구현

root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/request/TicketUpdateRequestDto.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/CategoryEnum.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/Ticket.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java
=> feat: 이용권 수정 구현

root/ticket-service/src/main/java/com/example/ticketservice/entity/LectureReservation.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/LectureWaiting.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/ReservationStatusEnum.java
- LectureReservation, LectureWaiting, ReservationStatusEnum 다시 이용권 서비스로 이동
- LectureWaitingList -> LectureWaiting 이름 변경
- LectureReservation에 lectureScheduleId, UserTicket 필드 추가
- LectureWaiting에 number 필드 삭제, memberId 추가
=> fix: 강의예약을 이용권 서비스로 이동

root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/TicketResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java
- 관리자 페이지의 수업, 이용권 관리 탭의 이용권 리스트 조회 구현
=> feat: 이용권 리스트 조회 구현

root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java
- 수업, 이용권 관리 탭 API는 management 접두사
- 예약, 리뷰 관리 탭 API는 review 접두사
=> refactor: 이용권 서비스 URI 변경

root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/Ticket.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java
=> feat: 이용권 업로드 구현

root/ticket-service/build.gradle, root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/request/ReviewRequestDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/request/TicketCreateRequestDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/AdminTicketResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/TicketResponseDto.java, root/ticket-service/src/test/java/com/example/ticketservice/AcceptanceTest.java, root/ticket-service/src/test/java/com/example/ticketservice/DatabaseCleanup.java, root/ticket-service/src/test/java/com/example/ticketservice/fixture/CenterFixture.java, root/ticket-service/src/test/java/com/example/ticketservice/fixture/ReviewFixture.java, root/ticket-service/src/test/java/com/example/ticketservice/fixture/TicketFixture.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/AdminTicketSteps.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/ReviewSteps.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/TicketAcceptanceTest.java, root/ticket-service/src/test/resources/application-test.yml
=> test: 이용권 인수테스트 작성

root/ticket-service/src/main/java/com/example/ticketservice/common/exception/ExceptionEnum.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/LectureReservationController.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/TicketCreateResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/TicketDetailResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/LectureReservation.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/Ticket.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/UserTicket.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/reservation/LectureReservationRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/ticket/UserTicketRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/service/LectureReservationService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/LectureReservationServiceImpl.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java, root/ticket-service/src/test/java/com/example/ticketservice/AcceptanceTest.java, root/ticket-service/src/test/java/com/example/ticketservice/fixture/CenterFixture.java, root/ticket-service/src/test/java/com/example/ticketservice/lecturereservation/LectureReservationAcceptanceTest.java, root/ticket-service/src/test/java/com/example/ticketservice/lecturereservation/LectureReservationSteps.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/AdminTicketSteps.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/TicketAcceptanceTest.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/TicketSteps.java
- 이용권 구매, 강의 예약 일부 구현(결제, 강의 서비스와의 통합은 추후 구현 예정)
- 이용권 구매 인수테스트 추가
- 예외 처리 enum 추가하여 적용
=> feat: 이용권 구매, 수업 예약 일부 구현

root/ticket-service/src/main/java/com/example/ticketservice/common/exception/ExceptionEnum.java, root/ticket-service/src/main/java/com/example/ticketservice/entity/Ticket.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/ticket/TicketRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java, root/ticket-service/src/test/java/com/example/ticketservice/fixture/TicketFixture.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/TicketServiceTest.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/TicketSteps.java
- 이용권 동시 구매 단위테스트 작성
- 비관적 락 적용하여 동시 구매 시 경쟁상태 처리
=> test: 이용권 동시 구매 단위테스트 작성, 처리

root/ticket-service/src/main/java/com/example/ticketservice/controller/ReviewController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/ReviewResponseDto.java, root/ticket-service/src/test/java/com/example/ticketservice/fixture/ReviewFixture.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/acceptance/TicketAcceptanceTest.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/utils/ReviewSteps.java
- 이용권 리뷰 조회 인수테스트 작성
- 이용권 리뷰 컨트롤러에서 관리자용 API URI 변경
=> test: 이용권 리뷰 인수테스트 작성

root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/RecentPurchaseUserTicketListResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/ticket/UserTicketRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/acceptance/TicketAcceptanceTest.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/utils/TicketSteps.java
- 내 최근 구매 이용권 내역 조회 구현
- 인수테스트 작성
=> feat: 내 최근 구매 이용권 내역 조회 구현

root/company-service/src/main/java/com/example/companyservice/controller/CenterClientController.java, root/company-service/src/main/java/com/example/companyservice/controller/CenterController.java, root/company-service/src/main/java/com/example/companyservice/dto/request/CompanyUpdateRequestDto.java, root/company-service/src/main/java/com/example/companyservice/dto/response/CenterInfoDetailResponseDto.java, root/company-service/src/main/java/com/example/companyservice/dto/response/CenterInfoResponseDto.java, root/company-service/src/main/java/com/example/companyservice/entity/Company.java, root/ticket-service/src/main/java/com/example/ticketservice/client/dto/response/CenterInfoResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/TicketDetailResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java, root/ticket-service/src/test/java/com/example/ticketservice/fixture/CenterFixture.java
- CenterInfoResponseDto에도 isLooppass, isRefundable 필드 추가
- CenterController, CenterClientController 분리
=> fix: Company에 isRefundable 필드 추가, DTO 등 수정

root/company-service/build.gradle, root/company-service/src/main/java/com/example/companyservice/controller/AdminCenterController.java, root/company-service/src/main/java/com/example/companyservice/dto/request/CompanyUpdateRequestDto.java, root/company-service/src/main/java/com/example/companyservice/dto/request/HourRequestDto.java, root/company-service/src/main/java/com/example/companyservice/entity/CenterBreakHour.java, root/company-service/src/main/java/com/example/companyservice/entity/CenterOperatingHour.java, root/company-service/src/test/java/com/example/companyservice/acceptance/AcceptanceTest.java, root/company-service/src/test/java/com/example/companyservice/acceptance/CenterAcceptanceTest.java, root/company-service/src/test/java/com/example/companyservice/acceptance/CompanyAcceptanceTest.java, root/company-service/src/test/java/com/example/companyservice/acceptance/DatabaseCleanup.java, root/company-service/src/test/java/com/example/companyservice/acceptance/steps/AdminCenterSteps.java, root/company-service/src/test/java/com/example/companyservice/acceptance/steps/CompanySteps.java, root/company-service/src/test/java/com/example/companyservice/fixture/CenterFixture.java, root/company-service/src/test/java/com/example/companyservice/fixture/CompanyFixture.java, root/company-service/src/test/resources/application-test.yml
- Company, Admin API 간단한 것만 인수테스트 작성
- 예약어 충돌로 인해 CenterBreakHour, CenterOperatingHour의 day 필드에 @Column(name = "`day`") 추가(DB에 들어가는 필드 이름이 바뀌는게 아니라 예약어 충돌만 피하기 위한 것)
=> test: company service 인수테스트 일부 작성

root/ticket-service/src/main/java/com/example/ticketservice/controller/AdminTicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/ReviewController.java, root/ticket-service/src/main/java/com/example/ticketservice/controller/TicketController.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/AdminMyTicketResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/AdminTicketResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/ReviewByCenterResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/TicketByCenterResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/TicketResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/dto/response/TicketReviewListByCenterResponseDto.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/review/ReviewRepositoryCustom.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/review/ReviewRepositoryImpl.java, root/ticket-service/src/main/java/com/example/ticketservice/repository/ticket/TicketRepository.java, root/ticket-service/src/main/java/com/example/ticketservice/service/ReviewService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/ReviewServiceImpl.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketService.java, root/ticket-service/src/main/java/com/example/ticketservice/service/TicketServiceImpl.java, root/ticket-service/src/test/java/com/example/ticketservice/fixture/CenterFixture.java, root/ticket-service/src/test/java/com/example/ticketservice/fixture/TicketFixture.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/acceptance/TicketAcceptanceTest.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/utils/AdminTicketSteps.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/utils/ReviewSteps.java, root/ticket-service/src/test/java/com/example/ticketservice/ticket/utils/TicketSteps.java
- 관리자, 사용자 페이지 등에서 이용권 조회 구현
- 휴무 로직 수정
=> feat: 이용권 조회 구현
